package com.loancalculator.finance.manager.utils.value

import com.loancalculator.finance.manager.PlfDealApplication
import com.loancalculator.finance.manager.R
import com.loancalculator.finance.manager.data.DataCurrencyRatePlf
import com.loancalculator.finance.manager.data.DataCurrencyUnitPlf
import com.loancalculator.finance.manager.data.DataToolsTemperature
import com.loancalculator.finance.manager.utils.LengthUnit
import com.loancalculator.finance.manager.utils.MassUnit
import com.loancalculator.finance.manager.utils.SpeedUnit
import com.loancalculator.finance.manager.utils.TemperatureUnit
import java.io.File

object ParamsLtdUtils {
    var mDataCurrencyUnitPlf: DataCurrencyUnitPlf? = null
    var mRateCurrencyPlf: DataCurrencyUnitPlf? = null

    var mExchangeRateList = mutableListOf<DataCurrencyRatePlf>()

    val mSaveFilePlf by lazy {
        File(
            PlfDealApplication.mPlfContext.filesDir,
            "PrecisionLoanFiles"
        ).apply {
            if (!exists()) {
                mkdir()
            }
        }
    }

    //温度的单位和名称
    val mTemperatureUnitList = listOf(
        TemperatureUnit.CELSIUS,
        TemperatureUnit.REAUMUR,
        TemperatureUnit.FAHRENHEIT,
        TemperatureUnit.KELVIN,
        TemperatureUnit.RANKINE,
    )

    //速度的单位和名称
    val mSpeedUnitList = listOf(
        SpeedUnit.LIGHT,
        SpeedUnit.KMS,
        SpeedUnit.KMH,
        SpeedUnit.MS,
        SpeedUnit.MH,
        SpeedUnit.INS,
        SpeedUnit.MACH,
    )

    //重量的单位和名称
    val mMassUnitList = listOf(
        MassUnit.QUINTAL,
        MassUnit.CARAT,
        MassUnit.TON,
        MassUnit.MILLIGRAM,
        MassUnit.KILOGRAM,
        MassUnit.GRAM,
    )
    //长度的单位和名称
    val mLengthUnitList = listOf(
        LengthUnit.KILOMETER,
        LengthUnit.HECTOMETER,
        LengthUnit.DECAMETER,
        LengthUnit.METER,
        LengthUnit.DECIMETER,
        LengthUnit.CENTIMETER,
        LengthUnit.MILLIMETER,
    )

    val mCurrencyListData = mutableListOf(
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_aud, "AUD", "Australian Dollar", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_brl, "BRL", "Brazilian Real", "R$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_cad, "CAD", "Canadian Dollar", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_chf, "CHF", "Swiss Franc", "CHF"),
        DataCurrencyUnitPlf(
            R.drawable.plf_til_currency_unit_cny,
            "CNY",
            "Chinese Renminbi Yuan",
            "¥"
        ),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_czk, "CZK", "Czech Koruna", "Kč"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_dkk, "DKK", "Danish Krone", "kr"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_eur, "EUR", "Euro", "€"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_gbp, "GBP", "British Pound", "£"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_hkd, "HKD", "Hong Kong Dollar", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_huf, "HUF", "Hungarian Forint", "Ft"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_idr, "IDR", "Indonesian Rupiah", "Rp"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_ils, "ILS", "Israeli New Shekel", "₪"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_inr, "INR", "Indian Rupee", "₹"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_isk, "ISK", "Icelandic Króna", "kr"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_jpy, "JPY", "Japanese Yen", "¥"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_krw, "KRW", "South Korean Won", "₩"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_mxn, "MXN", "Mexican Peso", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_myr, "MYR", "Malaysian Ringgit", "RM"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_nok, "NOK", "Norwegian Krone", "kr"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_nzd, "NZD", "New Zealand Dollar", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_php, "PHP", "Philippine Peso", "₱"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_pln, "PLN", "Polish Złoty", "zł"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_ron, "RON", "Romanian Leu", "lei"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_sek, "SEK", "Swedish Krona", "kr"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_sgd, "SGD", "Singapore Dollar", "$"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_thb, "THB", "Thai Baht", "฿"),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_try, "TRY", "Turkish Lira", "₺"),
        DataCurrencyUnitPlf(
            R.drawable.plf_til_currency_unit_usd,
            "USD",
            "United States Dollar",
            "$"
        ),
        DataCurrencyUnitPlf(R.drawable.plf_til_currency_unit_zar, "ZAR", "South African Rand", "R")
    )

    val mWorldTimeUtcList by lazy {
        mutableListOf(
            "Africa/Abidjan",
            "Africa/Accra",
            "Africa/Addis_Ababa",
            "Africa/Algiers",
            "Africa/Asmera",
            "Africa/Bamako",
            "Africa/Bangui",
            "Africa/Banjul",
            "Africa/Bissau",
            "Africa/Blantyre",
            "Africa/Brazzaville",
            "Africa/Bujumbura",
            "Africa/Cairo",
            "Africa/Casablanca",
            "Africa/Ceuta",
            "Africa/Conakry",
            "Africa/Dakar",
            "Africa/Dar_es_Salaam",
            "Africa/Djibouti",
            "Africa/Douala",
            "Africa/El_Aaiun",
            "Africa/Freetown",
            "Africa/Gaborone",
            "Africa/Harare",
            "Africa/Johannesburg",
            "Africa/Juba",
            "Africa/Kampala",
            "Africa/Khartoum",
            "Africa/Kigali",
            "Africa/Kinshasa",
            "Africa/Lagos",
            "Africa/Libreville",
            "Africa/Lome",
            "Africa/Luanda",
            "Africa/Lubumbashi",
            "Africa/Lusaka",
            "Africa/Malabo",
            "Africa/Maputo",
            "Africa/Maseru",
            "Africa/Mbabane",
            "Africa/Mogadishu",
            "Africa/Monrovia",
            "Africa/Nairobi",
            "Africa/Ndjamena",
            "Africa/Niamey",
            "Africa/Nouakchott",
            "Africa/Ouagadougou",
            "Africa/Porto-Novo",
            "Africa/Sao_Tome",
            "Africa/Tripoli",
            "Africa/Tunis",
            "Africa/Windhoek",
            "America/Anguilla",
            "America/Antigua",
            "America/Araguaina",
            "America/Argentina/Buenos_Aires",
            "America/Argentina/Catamarca",
            "America/Argentina/Cordoba",
            "America/Argentina/Jujuy",
            "America/Argentina/La_Rioja",
            "America/Argentina/Mendoza",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Salta",
            "America/Argentina/San_Juan",
            "America/Argentina/San_Luis",
            "America/Argentina/Tucuman",
            "America/Argentina/Ushuaia",
            "America/Aruba",
            "America/Asuncion",
            "America/Bahia",
            "America/Bahia_Banderas",
            "America/Barbados",
            "America/Belem",
            "America/Belize",
            "America/Blanc-Sablon",
            "America/Boa_Vista",
            "America/Bogota",
            "America/Boise",
            "America/Buenos_Aires",
            "America/Cambridge_Bay",
            "America/Campo_Grande",
            "America/Cancun",
            "America/Caracas",
            "America/Catamarca",
            "America/Cayenne",
            "America/Cayman",
            "America/Chicago",
            "America/Chihuahua",
            "America/Coral_Harbour",
            "America/Cordoba",
            "America/Costa_Rica",
            "America/Creston",
            "America/Cuiaba",
            "America/Curacao",
            "America/Danmarkshavn",
            "America/Dawson",
            "America/Dawson_Creek",
            "America/Denver",
            "America/Detroit",
            "America/Dominica",
            "America/Edmonton",
            "America/Eirunepe",
            "America/El_Salvador",
            "America/Fortaleza",
            "America/Glace_Bay",
            "America/Godthab",
            "America/Goose_Bay",
            "America/Grand_Turk",
            "America/Grenada",
            "America/Guadeloupe",
            "America/Guatemala",
            "America/Guayaquil",
            "America/Guyana",
            "America/Halifax",
            "America/Havana",
            "America/Hermosillo",
            "America/Indiana/Knox",
            "America/Indiana/Marengo",
            "America/Indiana/Petersburg",
            "America/Indiana/Tell_City",
            "America/Indiana/Vevay",
            "America/Indiana/Vincennes",
            "America/Indiana/Winamac",
            "America/Indianapolis",
            "America/Inuvik",
            "America/Iqaluit",
            "America/Jamaica",
            "America/Jujuy",
            "America/Juneau",
            "America/Kentucky/Monticello",
            "America/Kralendijk",
            "America/La_Paz",
            "America/Lima",
            "America/Los_Angeles",
            "America/Louisville",
            "America/Lower_Princes",
            "America/Maceio",
            "America/Managua",
            "America/Manaus",
            "America/Marigot",
            "America/Martinique",
            "America/Matamoros",
            "America/Mazatlan",
            "America/Mendoza",
            "America/Menominee",
            "America/Merida",
            "America/Mexico_City",
            "America/Moncton",
            "America/Monterrey",
            "America/Montreal",
            "America/Montserrat",
            "America/Nassau",
            "America/New_York",
            "America/Nipigon",
            "America/Nome",
            "America/Noronha",
            "America/North_Dakota/Beulah",
            "America/North_Dakota/Center",
            "America/North_Dakota/New_Salem",
            "America/Ojinaga",
            "America/Panama",
            "America/Pangnirtung",
            "America/Paramaribo",
            "America/Phoenix",
            "America/Port-au-Prince",
            "America/Port_of_Spain",
            "America/Porto_Velho",
            "America/Puerto_Rico",
            "America/Rainy_River",
            "America/Rankin_Inlet",
            "America/Recife",
            "America/Regina",
            "America/Resolute",
            "America/Rio_Branco",
            "America/Santa_Isabel",
            "America/Santarem",
            "America/Santiago",
            "America/Santo_Domingo",
            "America/Sao_Paulo",
            "America/Scoresbysund",
            "America/Sitka",
            "America/St_Barthelemy",
            "America/St_Johns",
            "America/St_Kitts",
            "America/St_Lucia",
            "America/St_Thomas",
            "America/St_Vincent",
            "America/Swift_Current",
            "America/Tegucigalpa",
            "America/Thunder_Bay",
            "America/Thule",
            "America/Tijuana",
            "America/Toronto",
            "America/Tortola",
            "America/Vancouver",
            "America/Whitehorse",
            "America/Winnipeg",
            "America/Yakutat",
            "America/Yellowknife",
            "Antarctica/Casey",
            "Antarctica/Davis",
            "Antarctica/DumontDUrville",
            "Antarctica/Macquarie",
            "Antarctica/Mawson",
            "Antarctica/McMurdo",
            "Antarctica/Palmer",
            "Antarctica/Rothera",
            "Antarctica/Syowa",
            "Antarctica/Vostok",
            "Arctic/Longyearbyen",
            "Asia/Aden",
            "Asia/Almaty",
            "Asia/Amman",
            "Asia/Aqtau",
            "Asia/Aqtobe",
            "Asia/Ashgabat",
            "Asia/Baghdad",
            "Asia/Bahrain",
            "Asia/Baku",
            "Asia/Bangkok",
            "Asia/Beirut",
            "Asia/Bishkek",
            "Asia/Brunei",
            "Asia/Calcutta",
            "Asia/Chita",
            "Asia/Choibalsan",
            "Asia/Colombo",
            "Asia/Damascus",
            "Asia/Dhaka",
            "Asia/Dili",
            "Asia/Dubai",
            "Asia/Dushanbe",
            "Asia/Hong_Kong",
            "Asia/Hovd",
            "Asia/Irkutsk",
            "Asia/Jakarta",
            "Asia/Jayapura",
            "Asia/Jerusalem",
            "Asia/Kabul",
            "Asia/Kamchatka",
            "Asia/Karachi",
            "Asia/Kathmandu",
            "Asia/Khandyga",
            "Asia/Kolkata",
            "Asia/Krasnoyarsk",
            "Asia/Kuala_Lumpur",
            "Asia/Kuching",
            "Asia/Kuwait",
            "Asia/Macau",
            "Asia/Magadan",
            "Asia/Makassar",
            "Asia/Manila",
            "Asia/Muscat",
            "Asia/Nicosia",
            "Asia/Novokuznetsk",
            "Asia/Novosibirsk",
            "Asia/Omsk",
            "Asia/Oral",
            "Asia/Phnom_Penh",
            "Asia/Pontianak",
            "Asia/Pyongyang",
            "Asia/Qatar",
            "Asia/Qyzylorda",
            "Asia/Rangoon",
            "Asia/Riyadh",
            "Asia/Saigon",
            "Asia/Sakhalin",
            "Asia/Samarkand",
            "Asia/Seoul",
            "Asia/Shanghai",
            "Asia/Singapore",
            "Asia/Srednekolymsk",
            "Asia/Taipei",
            "Asia/Tashkent",
            "Asia/Tbilisi",
            "Asia/Tehran",
            "Asia/Thimphu",
            "Asia/Tokyo",
            "Asia/Tomsk",
            "Asia/Ulaanbaatar",
            "Asia/Urumqi",
            "Asia/Ust-Nera",
            "Asia/Vientiane",
            "Asia/Vladivostok",
            "Asia/Yakutsk",
            "Asia/Yekaterinburg",
            "Asia/Yerevan",
            "Atlantic/Azores",
            "Atlantic/Bermuda",
            "Atlantic/Canary",
            "Atlantic/Cape_Verde",
            "Atlantic/Faeroe",
            "Atlantic/Madeira",
            "Atlantic/Reykjavik",
            "Atlantic/South_Georgia",
            "Atlantic/St_Helena",
            "Atlantic/Stanley",
            "Australia/Adelaide",
            "Australia/Brisbane",
            "Australia/Broken_Hill",
            "Australia/Currie",
            "Australia/Darwin",
            "Australia/Hobart",
            "Australia/Lindeman",
            "Australia/Melbourne",
            "Australia/Perth",
            "Australia/Sydney",
            "CST6CDT",
            "Etc/GMT",
            "Etc/GMT+1",
            "Etc/GMT+10",
            "Etc/GMT+11",
            "Etc/GMT+12",
            "Etc/GMT+2",
            "Etc/GMT+3",
            "Etc/GMT+4",
            "Etc/GMT+5",
            "Etc/GMT+6",
            "Etc/GMT+7",
            "Etc/GMT-1",
            "Etc/GMT-10",
            "Etc/GMT-11",
            "Etc/GMT-12",
            "Etc/GMT-13",
            "Etc/GMT-2",
            "Etc/GMT-3",
            "Etc/GMT-4",
            "Etc/GMT-5",
            "Etc/GMT-6",
            "Etc/GMT-7",
            "Etc/GMT-8",
            "Etc/GMT-9",
            "Europe/Amsterdam",
            "Europe/Andorra",
            "Europe/Athens",
            "Europe/Belgrade",
            "Europe/Berlin",
            "Europe/Bratislava",
            "Europe/Brussels",
            "Europe/Bucharest",
            "Europe/Budapest",
            "Europe/Busingen",
            "Europe/Chisinau",
            "Europe/Copenhagen",
            "Europe/Dublin",
            "Europe/Gibraltar",
            "Europe/Guernsey",
            "Europe/Helsinki",
            "Europe/Isle_of_Man",
            "Europe/Istanbul",
            "Europe/Jersey",
            "Europe/Kaliningrad",
            "Europe/Kirov",
            "Europe/Kyiv",
            "Europe/Lisbon",
            "Europe/Ljubljana",
            "Europe/London",
            "Europe/Luxembourg",
            "Europe/Madrid",
            "Europe/Malta",
            "Europe/Mariehamn",
            "Europe/Minsk",
            "Europe/Monaco",
            "Europe/Moscow",
            "Europe/Nicosia",
            "Europe/Oslo",
            "Europe/Paris",
            "Europe/Podgorica",
            "Europe/Prague",
            "Europe/Riga",
            "Europe/Rome",
            "Europe/Samara",
            "Europe/San_Marino",
            "Europe/Sarajevo",
            "Europe/Simferopol",
            "Europe/Skopje",
            "Europe/Sofia",
            "Europe/Stockholm",
            "Europe/Tallinn",
            "Europe/Tirane",
            "Europe/Ulyanovsk",
            "Europe/Uzhhorod",
            "Europe/Vaduz",
            "Europe/Vatican",
            "Europe/Vienna",
            "Europe/Vilnius",
            "Europe/Volgograd",
            "Europe/Warsaw",
            "Europe/Zagreb",
            "Europe/Zaporizhzhia",
            "Europe/Zurich",
            "Indian/Antananarivo",
            "Indian/Chagos",
            "Indian/Christmas",
            "Indian/Cocos",
            "Indian/Comoro",
            "Indian/Kerguelen",
            "Indian/Mahe",
            "Indian/Maldives",
            "Indian/Mauritius",
            "Indian/Mayotte",
            "Indian/Reunion",
            "MST7MDT",
            "Pacific/Apia",
            "Pacific/Auckland",
            "Pacific/Efate",
            "Pacific/Enderbury",
            "Pacific/Fakaofo",
            "Pacific/Fiji",
            "Pacific/Funafuti",
            "Pacific/Galapagos",
            "Pacific/Guadalcanal",
            "Pacific/Guam",
            "Pacific/Honolulu",
            "Pacific/Johnston",
            "Pacific/Kosrae",
            "Pacific/Kwajalein",
            "Pacific/Majuro",
            "Pacific/Midway",
            "Pacific/Nauru",
            "Pacific/Niue",
            "Pacific/Noumea",
            "Pacific/Pago_Pago",
            "Pacific/Palau",
            "Pacific/Ponape",
            "Pacific/Port_Moresby",
            "Pacific/Rarotonga",
            "Pacific/Saipan",
            "Pacific/Tahiti",
            "Pacific/Tarawa",
            "Pacific/Tongatapu",
            "Pacific/Truk",
            "Pacific/Wake",
            "Pacific/Wallis",
            "PST8PDT"
        )
    }
}